### ISSUE TITLE
combine with danfuzz/one-true-awk

### ISSUE THREAD

**Issue by josephholsten** [onetrueawk/awk#1]
It's silly to have two mirrors in github, you two should work together:
https://github.com/danfuzz/one-true-awk

**Comment by tinkster** [comment]
Heh. It's silly to tell the 'K' in 'awk' to join someone else's mirror of his creation. ;}

**Comment by josephholsten** [comment]
Too true. I didn't realize that when I created this ticket, thought both were mirrors.
Though I wouldn't mind if this repo contained tags for the historical releases so danfuzz's mirror was unnecessary (see https://github.com/danfuzz/one-true-awk/issues/11).

**Comment by onetrueawk** [comment]
The original is now up to date; I hope this will help.
