### ISSUE TITLE
Unexpected behavior with operators

### ISSUE THREAD

**Issue by SedapnyaTidur** [onetrueawk/awk#103]
Well first of all, I have no idea which one is right and which one is wrong. To me busybox awk's implemention seems right the others were wrong. But here some tests.

# Busybox awk

```
$ bawk 'BEGIN { print !"a" }'
0
$ bawk 'BEGIN { print !!"a" }'
1
$ bawk 'BEGIN { print !!!"a" }'
0
$ bawk 'BEGIN { print +"a" }'
0
$ bawk 'BEGIN { print ++"a" }'
1
$ bawk 'BEGIN { print +++"a" }'
1
$ bawk 'BEGIN { print -"a" }'
0
$ bawk 'BEGIN { print --"a" }'
-1
$ bawk 'BEGIN { print ---"a" }'
-1
```

# GNU awk

```
$ gawk 'BEGIN { print !"a" }'
0
$ gawk 'BEGIN { print !!"a" }'
1
$ gawk 'BEGIN { print !!!"a" }'
0
$ gawk 'BEGIN { print +"a" }'
0
$ gawk 'BEGIN { print ++"a" }'
gawk: cmd. line:1: BEGIN { print ++"a" }
gawk: cmd. line:1:                 ^ syntax error
$ gawk 'BEGIN { print +++"a" }'
gawk: cmd. line:1: BEGIN { print +++"a" }
gawk: cmd. line:1:                 ^ syntax error
$ gawk 'BEGIN { print -"a" }'
0
$ gawk 'BEGIN { print --"a" }'
gawk: cmd. line:1: BEGIN { print --"a" }
gawk: cmd. line:1:                 ^ syntax error
$ gawk 'BEGIN { print ---"a" }'
gawk: cmd. line:1: BEGIN { print ---"a" }
gawk: cmd. line:1:                 ^ syntax error
```

# One True awk

```
$ nawk 'BEGIN { print !"a" }'
0
$ nawk 'BEGIN { print !!"a" }'
1
$ nawk 'BEGIN { print !!!"a" }'
0
$ nawk 'BEGIN { print +"a" }'
0
$ nawk 'BEGIN { print ++"a" }'
nawk: syntax error at source line 1
 context is
        BEGIN { print >>>  ++"a" <<<
nawk: illegal statement at source line 1
$ nawk 'BEGIN { print +++"a" }'
nawk: syntax error at source line 1
 context is
        BEGIN { print >>>  +++ <<< "a" }
nawk: illegal statement at source line 1
$ nawk 'BEGIN { print -"a" }'
0
$ nawk 'BEGIN { print --"a" }'
nawk: syntax error at source line 1
 context is
        BEGIN { print >>>  --"a" <<<
nawk: illegal statement at source line 1
$ nawk 'BEGIN { print ---"a" }'
nawk: syntax error at source line 1
 context is
        BEGIN { print >>>  --- <<< "a" }
nawk: illegal statement at source line 1
$ nawk 'BEGIN { print --"a" }'
```

I can understand if double operators  (```++"string"```) throws an error but even with triple opeators like this (```+++"string"```), does not make any sense.
Shouldn't it convert ```"string"``` to decimal first .e.g. (```"string"+0```) then do the arithmetic operation? 
This behavior is so unconsistent with the following example:

```
 $ bawk 'BEGIN { print "999" + 1 }'
1000
 $ gawk 'BEGIN { print "999" + 1 }'
1000
 $ nawk 'BEGIN { print "999" + 1 }'
1000
```

THE END.

**Comment by SedapnyaTidur** [comment]
Well, I did another test.

# Busybox awk

```
bawk 'BEGIN { var="999"; print +var }'
999
$ bawk 'BEGIN { var="999"; print ++var }'
1000
$ bawk 'BEGIN { var="999"; print +++var }'
1000
```

# GNU awk

```
$ gawk 'BEGIN { var="999"; print +var }'
999
$ gawk 'BEGIN { var="999"; print ++var }'
1000
$ gawk 'BEGIN { var="999"; print +++var }'
gawk: cmd. line:1: BEGIN { var="999"; print +++var }
gawk: cmd. line:1:                            ^ syntax error
```

# One True awk

```
$ nawk 'BEGIN { var="999"; print +var }'
999
$ nawk 'BEGIN { var="999"; print ++var }'
1000
$ nawk 'BEGIN { var="999"; print +++var }'
nawk: syntax error at source line 1
 context is
        BEGIN { var="999"; print >>>  +++ <<< var }
nawk: illegal statement at source line 1
```
THE END.

**Comment by SedapnyaTidur** [comment]
Well, third time for the charm. Here another test which shows inconsistencies.

# Busybox awk

```
$ bawk 'BEGIN { var="str"; print +str }'
0
$ bawk 'BEGIN { var="str"; print ++str }'
1
$ bawk 'BEGIN { var="str"; print +++str }'
1
```

# GNU awk

```
$ gawk 'BEGIN { var="str"; print +str }'                      0
$ gawk 'BEGIN { var="str"; print ++str }'
1
$ gawk 'BEGIN { var="str"; print +++str }'
gawk: cmd. line:1: BEGIN { var="str"; print +++str }
gawk: cmd. line:1:                            ^ syntax error
```

# One True awk

```
$ nawk 'BEGIN { var="str"; print +str }'
0
$ nawk 'BEGIN { var="str"; print ++str }'
1
$ nawk 'BEGIN { var="str"; print +++str }'
nawk: syntax error at source line 1
 context is
        BEGIN { var="str"; print >>>  +++ <<< str }
nawk: illegal statement at source line 1
```
THE END.

**Comment by SedapnyaTidur** [comment]
Well, third time for the charm.

# Busybox awk

```
$ bawk 'BEGIN { var="str"; print +var }'
0
$ bawk 'BEGIN { var="str"; print ++var }'
1
$ bawk 'BEGIN { var="str"; print +++var }'
1
```

# GNU awk

```
$ gawk 'BEGIN { var="str"; print +var }'
0
$ gawk 'BEGIN { var="str"; print ++var }'
1
$ gawk 'BEGIN { var="str"; print +++var }'
gawk: cmd. line:1: BEGIN { var="str"; print +++var }
gawk: cmd. line:1:                            ^ syntax error
```
# One True awk

```
$ nawk 'BEGIN { var="str"; print +var }'
0
$ nawk 'BEGIN { var="str"; print ++var }'
1
$ nawk 'BEGIN { var="str"; print +++var }'
nawk: syntax error at source line 1
 context is
        BEGIN { var="str"; print >>>  +++ <<< var }
nawk: illegal statement at source line 1
```

**Comment by iamleot** [comment]
Hello @SedapnyaTidur,
The `++` and `--` operators should be applied to an `lvalue` where is defined in POSIX as «lvalue represents any entity that can be assigned to (that is, on the left side of an assignment operator)» (from [awk, The Open Group Base Specifications Issue 7, 2018 edition](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html)).

In the first example you have shared the `++` is not applied to an `lvalue` (in the grammar that would be a `STRING`).

**Comment by SedapnyaTidur** [comment]
@iamleot 
Well, thats proprably right but in awk, when a scalar does arithmetic with a decimal, awk will convert it to decimal. So when ```+"str"``` works just fine and ```+++"str"``` does not, how do you wanna explain that?

**Comment by iamleot** [comment]
> Well, thats proprably right but in awk, when a scalar does arithmetic with a decimal, awk will convert it to decimal. So when `+"str"` works just fine and `+++"str"` does not, how do you wanna explain that?

It's pretty similar.

In `+"str"` `str` is converted to a number and hence the 0 (it would be `+0`).
In `+++"str"` there is still something that is not an `lvalue` but a `STRING` or a `NUMBER`.

**Comment by SedapnyaTidur** [comment]
Well, I guess guess I was wrong then. ```++digit``` is not possible but ```++string``` does.

**Comment by iamleot** [comment]
> Well, I guess guess I was wrong then. `++digit` is not possible but `++string` does.

What are `digit` or `string`? :) (sorry to be picky but if they are not something like an `lvalue` that would not work)

**Comment by iamleot** [comment]
Err, to clarify further my previous comment:

```awk
++"str"
```

would not work because "str" is a `STRING` and not an `lvalue` while:

```awk
var = "str"
++var
```

would work because `var` is an `lvalue`.

**Comment by SedapnyaTidur** [comment]
I meant assigned variable actually like this. ```var=999; ++var```  and not just ```++"unsigned_var"```.

**Comment by SedapnyaTidur** [comment]
Thanks for clear up though. I am writing a javascript interpreter in awk and stumbled with these kind of things```++[], +++[], ![]```. So I am a bit confused though. Whahahhaaahaa...

**Comment by arnoldrobbins** [comment]
Note that there is no "triple operator" +++ or ---.  `+++a` is the same as `++ +a`.  Unary plus exists as a complement to unary minus, but doesn't do anything to the value (other than convert a string to numeric if necessary).

In terms of !, remember that a value in awk is considered to be true if it is EITHER non-zero OR non-null. Thus "a", while equal to numeric zero, is not a null string, so it is true. Thus `! "a"` yields 0, for false.

**Comment by SedapnyaTidur** [comment]
Well I have no idea you cannot assign ++ with decimal value, ```++1``` will throw an error. So that mean ```++``` or ```--``` must be assign to a variable not to a string. ```var=1; ++var``` or this ```++unsigned_var``` are ok but not this ```++"var"```.
