### ISSUE TITLE
Possible undefined behaviour of `ctype(3)` in `b.c:relex()` when using multiple `[:...:]` character classes in bracket expressions

### ISSUE THREAD

**Issue by iamleot** [onetrueawk/awk#11]
When using multiple `[:...:]` character classes in a bracket expression (and with
a non-C locale (e.g. `en_US.UTF-8`)) only the first one seems honored, e.g.:

    % echo "UPPER" | ./a.out '/[[:lower:][:upper:]]/ { print }'

should print `UPPER` but does not print it.

Inspecting that via the `-d` option we can indeed see that the [:upper:] is not
expanded in cclenter():

    % ./a.out -d '/[[:lower:][:upper:]]/ { print }'
    [...]
    lex token 47
    lex REGEXPR
    lex token 47
    reparse <[[:lower:][:upper:]]>
    cclenter: in = |abcdefghijklmnopqrstuvwxyz|, out = |abcdefghijklmnopqrstuvwxyz|
    lex token 123
    [...]

After some debugging it seems it is actually triggered by the following code
in `b.c`:

    826                                          for (i = 0; i < NCHARS; i++) {
    827                                                  if (!adjbuf((char **) &buf, &bufsz, bp-buf+1, 100, (char **) &bp, "relex2"))
    828                                                      FATAL("out of space for reg expr %.10s...", lastre);
    829                                                  if (cc->cc_func(i)) {
    830                                                          *bp++ = i;
    831                                                          n++;
    832                                                  }
    833                                          }

`cc_func()` is a `ctype(3)` function and `NCHARS` is `(256+3)`, so
also `cc->cc_func(256)`, `cc->cc_func(257)` and `cc->cc_func(258)`
can be invoked leading to a possible undefined behaviour.

(I will share a patch that changes `< NCHARS` to `<= UCHAR_MAX` in the
next minutes but of course any possible other suggestions to avoid
that is welcomed! Thank you very much!)

**Comment by arnoldrobbins** [comment]
@iamleot I remember trying this under Linux when you first posted the issue and seeing the problem you describe.  But now when I try it (Ubuntu 12.04 and 18.04) using the current code base, the bug does not reproduce. Are you still seeing this on *BSD?  Thanks.

**Comment by iamleot** [comment]
Hello Arnold,

Arnold Robbins writes:
> @iamleot I remember trying this under Linux when you first posted the issue and seeing the problem you describe.  But now when I try it (Ubuntu 12.04 and 18.04) using the current code base, the bug does not reproduce. Are you still seeing this on *BSD?  Thanks.

Yes, I am still seeing this on NetBSD.

I think that it isn't reproducible outside NetBSD libc (but maybe
there can be libc that can expose similar behaviour) because I
think that most of them for ctype(3) (internally) casts the `int'
argument to `unsigned char'.

However, according POSIX, e.g. for islower(3) (this apply to all
other ctype(3) functions):

 <http://pubs.opengroup.org/onlinepubs/9699919799/functions/islower.html>

(Relevant paragraph directly quoted here for convenience):

> [...in the synopsis islower() prototype is defined as         ...]
> [...                                                          ...]
> [...  int islower(int c);                                     ...]
> [...                                                          ...]
> The c argument is an int, the value of which the application shall
> ensure is a character representable as an unsigned char or equal
> to the value of the macro EOF. If the argument has any other value,
> the behavior is undefined.


Thank you!
