### ISSUE TITLE
Add str_pad function to the AWK

### ISSUE THREAD

**Issue by saeeddhqan** [onetrueawk/awk#114]
I want to add a new built-in function to the AWK as a PR that add a string to a certain length with another string:

str_pad(str, pad, len, type)

- **str(string):** input string.
- **pad(string):** pad string.
- **len(int):** If len is negative, returns the input string. Otherwise, the function adds a pad to the string until it reaches the size of len.
- **type(int):** type could be -1, 0, and 1. by default it is -1, which means the pad adds on the right side(default mode). 0 means both sides. -1 means left side.

```bash
IN: awk 'BEGIN {printf str_pad("init", "_", 6, -1)"\n"}'
OUT: __init
IN: awk 'BEGIN {printf str_pad("init", "_", 8, 0)"\n"}'
OUT: __init__
IN: awk 'BEGIN {printf str_pad("init", "_", 6, 1)"\n"}'
OUT: init__
```
Can I do that?
Thank you.

**Comment by arnoldrobbins** [comment]
@plan9 will have to make a final call on this.  However, it's a simple bit of coding that can be done adequately as an awk level function; I don't see a big need to add this to the one true awk.  Just my personal opinion, of course.

**Comment by saeeddhqan** [comment]
If it wouldn't be useful. I have another idea.
How about a word wrapper?
It will wrap each line based on words(Though it can be used for characters).
wrapper(str, char_len, break_str, cut_long_words)

- **str(string):** input string.
- **char_len(int):** Number of characters for each line. By default, it could be 80 chars.
- **break_str(string):** After each line it puts this string at the end of the line. By default, it could be a \n.
- **cut_long_words(bool or int):** if it's true, the line will cut by the way. By default, it could be 0. If this option is 1, it exactly acts as a simple wrapper.

```bash
IN: awk 'BEGIN {printf wrapper("With experience comes wisdom, and with wisdom comes experience", 32, "\n") "\n"}'
OUT: With experience comes wisdom,
and with wisdom comes experience
IN: awk 'BEGIN {printf wrapper("This is a biiiiiiiiiiiiiiiiiiiiiiiiiig deal", 5, "\n", 1) "\n"}'
OUT: This
is a
biiii
iiiii
iig
deal
IN: awk 'BEGIN {printf wrapper("This is a biiiiiiiiiiiiiiiiiiiiiiiiiig deal", 5, "\n", 0) "\n"}'
OUT: This
is a
biiiiiiiiiiig
deal
```
Is it good?

**Comment by plan9** [comment]
hi saeed, there are no immediate plans to add new built-in functions to onetrueawk, so a PR would be a waste of time.
