### ISSUE TITLE
awk can't build against tcc

### ISSUE THREAD

**Issue by kawaiiamber** [onetrueawk/awk#115]
Changing `HOSTCC` to `HOSTCC = tcc -g -Wall -pedantic -Wcast-qual` in the `makefile` results in make errors with tcc at `lib.c`
```
tcc -g -Wall -pedantic -Wcast-qual   -O2   -c -o lib.o lib.c
lib.c:636: error: incompatible types for redefinition of 'cmdname'
make: *** [<builtin>: lib.o] Error 1
```
It does, however, build against gcc. Tested against the current `staging` branch, `master` branch, and the one release tag.

system:
musl libc
tcc
bison (instead of yacc)
Also, the `-pedantic` flag should probably be `-Wpedantic` to be more portable.

**Comment by plan9** [comment]
thanks for the report, I'll take a look.

**Comment by arnoldrobbins** [comment]
Setting `HOSTCC = tcc` in the `makefile` and using the current code from the tinycc `mob` branch, awk builds without error.  This is on Ubuntu 18.04.  Closing this issue.

**Comment by kawaiiamber** [comment]
Using latest release of `tcc` still results in
```
lib.c:636: error: incompatible types for redefinition of 'cmdname'
```
Also, another variable - as mentioned - I use musl libc instead of glibc.

**Comment by arnoldrobbins** [comment]
Note what I said: The current code from the mob branch -- in the tinycc repo. The released version is very old. If you `git clone git://repo.or.cz/tinycc.git` and build that code, you'll get a tcc that will compile awk without problems.  musl libc vs. glibc doesn't matter here.
