### ISSUE TITLE
multiple threads in sort within awk to accelerate the speed

### ISSUE THREAD

**Issue by Shicheng-Guo** [onetrueawk/awk#120]
I am trying to use sort within awk and use multiple threads to accelerate the speed. However, I didn't notice the system try to use multiple threads, any suggestion? Thanks. 
```
zcat $1 | awk '{print $2,$3,$4,$5,$2"-"$3"-"$4"-"$5}'|awk 'NR == 1;NR>1{print $0|"sort --parallel=50 -k1,1 -k2,2n"}' OFS="\t"| bgzip > $1.jnj.gz
```
![image](https://user-images.githubusercontent.com/6641283/120076608-61886480-c074-11eb-8288-9ed43f3e756a.png)

**Comment by arnoldrobbins** [comment]
You would probably be better off pulling the sort command out of awk and just running it as a stage in the pipeline. The second awk stage could be replaced with `sed 1d`.  Although you set OFS on the command line, it has no effect as you are printing $0 as it comes into awk and not doing anything to rebuild the record.

You may wish to read up on awk programming, either the original awk book by Aho, Kernighan, and Weinberger, or the gawk manual.  Closing this issue.
