### ISSUE TITLE
feature request: -f like option, but the last one processed

### ISSUE THREAD

**Issue by phillbush** [onetrueawk/awk#125]
When writing a awk script that parses its arguments, it's sometimes useful to pass to the script an option-like argument (such as `-n`). But awk process those arguments and do not pass them to the script.

For example, consider this script `echo.awk`.

```
#!/usr/bin/awk -f

BEGIN {
	if (ARGV[1] == "-n")
		nl = 1
	for (i = nl + 1; i < ARGC; i++)
		printf (i == nl + 1 ? "" : " ") ARGV[i]
	if (!nl)
		print ""
}
```

Now call it with the following arguments:

```
$ echo.awk -n Hello World
awk: unknown option -n ignored
Hello World
$
```

The argument `-n` is not passed to the script. It is, however, processed by `awk(1)` and ignored. If it were an option known by awk, the behavior can be totally different from the expected.  To obtain the expected behavior, we need to call the script with the option after a `--`.

```
$ ./echo.awk -- -n Hello World
Hello World$
```

I'm asking for an option for onetrueawk that, like `-f`, reads a program from a file; but, unlike `-f`, is the last option to be parsed, and pass all following arguments (including option-like arguments) to the script.

This new option would be extremely useful in shebangs on awk scripts.

**Comment by plan9** [comment]
I'm afraid such an option is not likely to appear on OTA anytime soon. i understand
that "--" looks odd in some uses, but popular awk implementations agree on "--" as the end of options.

**Comment by phillbush** [comment]
I understand.  
I'll wrap my OTA scripts in a shell script that processes arguments with `getopt(1)` and pass them to the awk script via awk's `-v` option.  
In any case, other popular awk implementations have such a option that reads a program from a file and that is the last one to be processed, although they do not agree on the letter for such option: It's `-E` in gawk(1) and a `-W` suboption in mawk(1).

**Comment by drawkula** [comment]
> I'm asking for an option for onetrueawk that, like -f, reads a program from a file; but, unlike -f, is the last option to be parsed, and pass all following arguments (including option-like arguments) to the script.

Every AWK should have this option implemented in the same way and name.  I miss it most in (OpenWrt's) BusyBox-AWK but it only would have a chance if all AWKs adopt it.
