### ISSUE TITLE
Regression in hex conversions

### ISSUE THREAD

**Issue by bsdimp** [onetrueawk/awk#126]
Prior to cc9e9b68d124c6c7770eb3903329423ff9f17201 something like
```
echo abc | awk '{printf("%d\n", "0x" $1);}'
```
would print 2748. This is the number you also get with 'gawk -Wposix'.
Now '0' is printed. It is my opinion that the 'new' behavior existed for too long to revert back to the old, pre C99 behavior.

This change breaks awk scripts in the FreeBSD kernel build. All hex numbers are now converted to 0.

The latest standard allows either behavior, alas, so I can't point there to have it say definitively.

> Historical implementations of awk did not parse hexadecimal integer or floating constants like "0xa" and "0xap0". Due to an oversight, the 2001 through 2004 editions of this standard required support for hexadecimal floating constants. This was due to the reference to atof(). This version of the standard allows but does not require implementations to use atof() and includes a description of how floating-point numbers are recognized as an alternative to match historic behavior. The intent of this change is to allow implementations to recognize floating-point constants according to either the ISO/IEC 9899:1990 standard or ISO/IEC 9899:1999 standard, and to allow (but not require) implementations to recognize hexadecimal integer constants.

This is somewhat surprising to our users as well.

**Comment by plan9** [comment]
thank you for the report.

**Comment by bsdimp** [comment]
I can produce a fix for this. Reverting the above commit fixes is, but has too large a blast radius. A minimal fix to grok hex strings doesn't look to be terribly hard. I'd rather not take the time, though, if there is no chance a pull-request like that would be accepted.

**Comment by bsdimp** [comment]
```
diff --git a/contrib/one-true-awk/lib.c b/contrib/one-true-awk/lib.c
index 18adbd2d1fd6..9eb6260b8148 100644
--- a/contrib/one-true-awk/lib.c
+++ b/contrib/one-true-awk/lib.c
@@ -793,9 +793,18 @@ bool is_valid_number(const char *s, bool trailing_stuff_ok,
        while (isspace(*s))
                s++;

+/*
+ * This change, while allowed by newer POSIX standards, represents a regression
+ * where hex strings were treated as numbers in nawk the whole time it has been
+ * in FreeBSD (since 2001). The POSIX 2001 through 2004 standards mandated this
+ * behavior and the current standard allows it. Deviate from upstream by restoring
+ * the prioer FreeBSD behavior.
+ */
+#if 0
        // no hex floating point, sorry
        if (s[0] == '0' && tolower(s[1]) == 'x')
                return false;
+#endif

        // allow +nan, -nan, +inf, -inf, any other letter, no
        if (s[0] == '+' || s[0] == '-') {
````
is the change I've committed upstream.

This broke the program that generated some offsets in structures because
sorting went from numberical order (eg 0xf4 is before 0x142) to lexical order
(where it is after). This caused function padding to be all off because the
code / math assumes strictly numerically increasing values. This breakage
was silent (no warning was issued) and people couldn't build kernels who
had updated their awk, though it took days to work out this was the common
reason why.

There are other scripts as well that were broken, but broke in a noisy way
which prompted me to file the bug in the first place.

This reinforces the opinion I shared earlier, and offers, I suggest, more evidence
that more existing scripts would break than would be fixed by the shift in
interpretation of the standard.

**Comment by arnoldrobbins** [comment]
In my not-so-humble opinion, FreeBSD should fix its scripts. They were relying on an accident of the implementation. Even gawk's default is to not interpret hex data in the fashion you wish.  Since the standard is wishy-washy, you should go the other way towards the stricter behavior of original practice, and only use decimal values, or else write an explicit function that converts hex string values to numbers.  My two cents, of course.

**Comment by plan9** [comment]
warner, I agree with arnold. I'm sorry that FreeBSD builds having problems due to this issue. you are right a PR would be a waste of time.

**Comment by plan9** [comment]
I'll note in passing that mike brennan's authoritative version of mawk (i happen to have 1.9.9.x) also matches our behaviour.

**Comment by bsdimp** [comment]
I've already re-written the build scripts that I know were affected (one was 1/2 the size in sh anyway, one someone else rewrote in lua in part to get bignum for expanding its functionality). My current plans are to keep the 2001-2020 ota behavior in the FreeBSD stable branches through the end stable/13 life cycles (because we try really hard not to user-visible change behavior mid-stable branch, and I don't know how many people depend on this behavior, not least because our downstream users tend to reuse things like our build scripts tweaked a bit). Leaves me a bit uneasy looking for the other ones that might be lurking...
