### ISSUE TITLE
awk -F '' and awk -v FS='' treated differently

### ISSUE THREAD

**Issue by bsdimp** [onetrueawk/awk#127]
While the 1003-2008 standard says that FS='' is undefined, one true awk treats this like every character is its own $n variable. This is documented in awk(1):

> If FS is null, the input line is split into one field per character.

The man page does not mention that the separator string must be non-null in its description of -F.

This means that `echo foo | awk -v FS='' '{ print $1; }'` will print 'f', however `echo foo | awk -F '' '{ print $1;}'` will print a warning: `awk: field separator FS is empty`.

1003-2008 also states that -F sepstring and -v FS=sepstring are identical:

> -F  sepstring
>Define the input field separator. This option shall be equivalent to:
> -v FS=sepstring

This suggests to me that the warning is invalid and it should be set to the empty string, given the behavior documented in the manual. This would be the most conservative interpretation of the standard, and would also give useful behavior.  A patch looks to be relatively straight forward, but I thought I'd file an issue first to make sure there's consensus around this detail before producing it.

**Comment by bsdimp** [comment]
I'll note both gawk and mawk also honor the FS='' convention of BWK.

**Comment by plan9** [comment]
you're correct, this inconsistency will need to be fixed.

**Comment by bsdimp** [comment]
https://github.com/onetrueawk/awk/pull/128 I believe addresses this.

**Comment by plan9** [comment]
thanks for the fix. both regression tests and the general tests are going to be overhauled,
i made a note to add a test for the -F / -v FS consistency.

**Comment by bsdimp** [comment]
Thanks!
