### ISSUE TITLE
awk: need to escape regexp delimiter (/) inside square brackets in a regex

### ISSUE THREAD

**Issue by phillbush** [onetrueawk/awk#140]
One True AWK needs the regexp delimiter / to be escaped even when between square brackets in a regexp.  
In the image, I compare the following command in GNU awk, mawk, OpenBSD awk and One True AWK.  
It works in all awk implementations, except in OTA.

```
awk 'BEGIN {s = "/"; sub(/[/]/, "a", s); print s}'
```

![ota](https://user-images.githubusercontent.com/63266536/148699403-040b734d-e95d-4508-9651-018d0d04c578.png)

**Comment by plan9** [comment]
you should have visited previously closed issues, #135 and #81 
this will not be fixed in onetrueawk for now.
thanks
