### ISSUE TITLE
Add new tag

### ISSUE THREAD

**Issue by carlosala** [onetrueawk/awk#141]
Hi!
Would be great to add a new tag to master, since there has been many commits since latest one. Doing this, repos (such as Archlinux one) could easily update their versions.
Thanks!

**Comment by plan9** [comment]
even though we don't generally add tags, I understand the usefulness. I will add a new tag soon.

**Comment by carlosala** [comment]
thanks!

**Comment by alerque** [comment]
Thanks for considering this. As the maintainer for the Arch Linux [nawk package](https://archlinux.org/packages/community/x86_64/nawk/) I can say this will make it a lot more likely for improvements to hit distro packaging. We have specific rules *against* releasing anything upstream hasn't indicated as a release into official repos unless we don't have any other option (e.g. unreleased dependencies blocking other released software / unable to build stable releases / etc.). I've seen user requests to update `nawk`, but without a tag it's kind of hard to justify it.

It doesn't have to be fancy if you don't want to deal with versioning, just add a dated tag now and then at any point you feel like the project is expected to work as advertised.

**Comment by plan9** [comment]
tag 20220122 has been added.

**Comment by alerque** [comment]
Thanks! The Arch Linux [nawk](https://archlinux.org/packages/community/x86_64/nawk/) package has been updated accordingly.
