### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [onetrueawk/awk#148]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@fish98) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by plan9** [comment]
current maintainer email address (mine) is in readme. I may check in a SECURITY.md file later.

**Comment by JamieSlome** [comment]
@plan9 - I just sent an e-mail to the address specified in the `README.md` 👍 

Just for reference, you can also find the report here:
https://huntr.dev/bounties/7272cdd2-c45a-4bbd-b13e-07c7d1c8e60b/
