### ISSUE TITLE
Ancient awk regexp compatibility bug

### ISSUE THREAD

**Issue by arnoldrobbins** [onetrueawk/awk#161]
Using the code from master as of today, I found the following bug. Given:

```sh
BEGIN {
	print match("abc-def", /[qrs---tuv]/)
}
```

The One True Awk prints a result of 0, whereas gawk and mawk print 4.  Ancient awks (and I think it's even documented in the awk book) allowed a "range" of minus through minus to mean a real actual minus sign.  The current code doesn't support this anymore.

**Comment by plan9** [comment]
that regexp engine is really showing its age... :-P

**Comment by plan9** [comment]
interesting find. thanks

**Comment by arnoldrobbins** [comment]
Harumph. It looks like plain matching of --- works:
```
$ echo xxx-y | ./a.out '/[a---q]/'
xxx-y
```

So maybe it's just an issue with the`match()` function?

**Comment by mpinjr** [comment]
Hi arnold, plan9:

In the following test program, each print statement pairs a match function and operator. They should both return the number 1.

```
BEGIN {
	s = "-"
	print "/[---]/", match(s, /[---]/), (s ~ /[---]/)
	print "/[x---]/", match(s, /[x---]/), (s ~ /[x---]/)
	print "/[---y]/", match(s, /[---y]/), (s ~ /[---y]/)
	print "/[x---y]/", match(s, /[x---y]/), (s ~ /[x---y]/)
	print "/[wx---y]/", match(s, /[wx---y]/), (s ~ /[wx---y]/)
	print "/[wx---]/", match(s, /[wx---]/), (s ~ /[wx---]/)
	print "/[---yz]/", match(s, /[---yz]/), (s ~ /[---yz]/)
	print "/[wx---yz]/", match(s, /[wx---yz]/), (s ~ /[wx---yz]/)
}

# Correct output
#
# /[---]/ 1 1
# /[x---]/ 1 1
# /[---y]/ 1 1
# /[x---y]/ 1 1
# /[wx---y]/ 1 1
# /[wx---]/ 1 1
# /[---yz]/ 1 1
# /[wx---yz]/ 1 1
```

Current gawk passes, but onetrueawk's master branch ([9e248c3](https://github.com/onetrueawk/awk/commit/9e248c317b88470fc86aa7c988919dc49452c88c)) fails with this output:
```
/[---]/ 1 1
/[x---]/ 1 1
/[---y]/ 1 1
/[x---y]/ 1 1
/[wx---y]/ 0 0
/[wx---]/ 1 1
/[---yz]/ 1 1
/[wx---yz]/ 0 0
```
Since the match functions always agree with their operator, I would guess that its a character class parsing issue.  Among these test cases, the bug only manifests when there are two characters before the triple-dash and one after.

Take care,
Miguel

**Comment by plan9** [comment]
hi miguel, apologies for the late response, this is correct, I have tested and found this weeks ago. I'm not clear on a clean fix at the moment.

**Comment by plan9** [comment]
triple minus should not be called an idiom. i think it is a twisted construct that happens to work with basic regular expression engines [including one I built decades ago] but in combination with other characters in the range, may or may not work, depending on the engine. not many implementors will go through the kind of contortions eg. mawk regex engine goes through to handle this, and nor should they.

**Comment by arnoldrobbins** [comment]
Let's close this issue since it's not going to change.
