### ISSUE TITLE
gsub and sub does not take "&"

### ISSUE THREAD

**Issue by hallenstal** [onetrueawk/awk#172]
awk version 20200816 on Mac 13.0.1

get the following using sub:
awk 'BEGIN {s="qwerty xxxx"; s2=s; s3=s;  sub(/xxxx/,"&",s); sub(/xxxx/,"\046",s2);sub(/xxxx/,"!!",s3);print s,s2,s3}' 
qwerty xxxx qwerty xxxx qwerty !!

and sub:
awk 'BEGIN {s="qwerty xxxx"; s2=s; s3=s;  gsub(/xxxx/,"&",s); gsub(/xxxx/,"\046",s2);gsub(/xxxx/,"!!",s3);print s,s2,s3}'
qwerty xxxx qwerty xxxx qwerty !!

is there a reason why you can't substitute to "&"?

**Comment by hallenstal** [comment]
some more interesting stuff regarding "&"
awk 'BEGIN {s="qwerty xxxx"; s2=s; s3=s;  sub(/xxxx/,"&&&&&&&&&",s);;print s}'
qwerty xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by hallenstal** [comment]
workaround
awk 'BEGIN {s="qwerty xxxx579";  match(s,/xxxx/); s=substr(s,1,RSTART-1) "&" substr(s,RSTART+RLENGTH);print s}'

**Comment by plan9** [comment]
I'm not sure I understand this discussion. do you feel that this behaviour violates the standard, or is inconsistent between the implementations?

**Comment by hallenstal** [comment]
command: 
 awk 'BEGIN {s="qwerty xxxx"; s2=s; s3=s; sub(/xxxx/,"&",s); sub(/xxxx/,"\046",s2);sub(/xxxx/,"!!",s3);print s,s2,s3}'

result:
qwerty xxxx qwerty xxxx qwerty !!

this shows that sub() does not substitute regular expression for "&", but it does it for all other characters e.g. "!" as seen by the example above. "xxxx" is not replaced when replacement string is "&" but it is replaced if other string e.g. "!"

**Comment by plan9** [comment]
you do realize "&" is special, right? 

>  "in a substitution performed by either sub(_r, s, t_) or gsub(_r, s, t_), any occurrance of the character & in _s_ will be replaced by the substring matched by _r_."
