### ISSUE TITLE
build assumes C compiler is gcc

### ISSUE THREAD

**Issue by emaste** [onetrueawk/awk#176]
Trying to build out of the box on FreeBSD results in:
```
$ make
gcc -g -Wall -pedantic -Wcast-qual  -O2 -c awkgram.tab.c -o awkgram.tab.o
make: exec(gcc) failed (No such file or directory)
*** Error code 1
```

**Comment by plan9** [comment]
you're right, bsd-features makefile is not correct for typical out of the box freebsd. bison, gcc etc. 
i'll clean that up.
