### ISSUE TITLE
Incorrect value for RSTART on UTF-8 string

### ISSUE THREAD

**Issue by arnoldrobbins** [onetrueawk/awk#188]
Hi. The program below incorrectly sets `RSTART` in the second call to `match()`.  This is a slightly modified version of a program submitted for a similar bug in gawk.

```awk
BEGIN {
	str="\342\200\257"
	print length(str)
	match(str,/.+/)
	print RSTART, RLENGTH
	match(str,/$/)
	print RSTART, RLENGTH
}
```

When I run it, I get this:

```
$ ./a.out -f /tmp/morton.awk 
1
1 1
-1 0
```

In the last line, the start value should be 2.  FWIW, the gawk bug was that `RSTART` was 4; it was using byte counts instead of character counts.

**Comment by plan9** [comment]
[oof] thanks arnold!

**Comment by plan9** [comment]
found the bug, it came with the unicode changes.
