### ISSUE TITLE
Regexp matches of the null string are incorrect

### ISSUE THREAD

**Issue by arnoldrobbins** [onetrueawk/awk#189]
Hi. Just so that I don't have to suffer alone, here's a hot-off-the-presses bug report that the OTA shares with `gawk`:

```sh
$ cat /tmp/x.awk
BEGIN {
	str = "\342\200\257"
	n = gsub(//, "X", str)
	print n, str
}
$ ./a.out -f /tmp/x.awk
4 X�X�X�X
```

This occurs in master. (Congrats, BTW, on merging the `csv` branch).

Thanks!

**Comment by plan9** [comment]
thanks(!) for this. interesting.

**Comment by plan9** [comment]
thank you @arnoldrobbins for the fix.
