### ISSUE TITLE
awk 2023 please :-)

### ISSUE THREAD

**Issue by ajaynshah** [onetrueawk/awk#192]
We are at a historic moment -- https://www.awk.dev/

One feature, --csv, is important. 

It should come into this package!

It seems this integration into gawk is also presently underway.

**Comment by plan9** [comment]
hi ajay, indeed it is. also --csv is already in onetrueawk 2ndEdition release.

**Comment by plan9** [comment]
hi ajay, indeed it is. also --csv is already in onetrueawk 2ndEdition release.
