### ISSUE TITLE
LICENCIA

### ISSUE THREAD

**Issue by DIEGOHJJACOBO** [onetrueawk/awk#202]
This section attempts to summarize the position of OpenBSD relative to some commonly encountered copyrights.

Berkeley
The Berkeley copyright is the model for the OpenBSD copyright. It retains the rights of the copyright holder, while imposing minimal conditions on the use of the copyrighted material. Material with Berkeley copyrights, or copyrights closely adhering to the Berkeley model can generally be included in OpenBSD.

AT&T
As part of its settlement with AT&T, Berkeley included an AT&T copyright notice on some of the files in 4.4BSD lite and lite2. The terms of this license are identical to the standard Berkeley license.

Additionally, OpenBSD includes some other AT&T code with non-restrictive copyrights, such as the reference implementation of awk.

**Comment by arnoldrobbins** [comment]
The current Lucent license is quite permissive, and as was noted, we're not in a position to change it. @plan9 is there a reason to keep this issue open?
