### ISSUE TITLE
The ISC copyright is functionally equivalent to a two-term BSD copyright with language removed that is made unnecessary by the Berne convention. This is the preferred license for new code incorporated into OpenBSD. A sample license is available in the file

### ISSUE THREAD

**Issue by DIEGOHJJACOBO** [onetrueawk/awk#203]
https://cvsweb.openbsd.org/src/share/misc/license.template?rev=HEAD

**Comment by plan9** [comment]
first, issue headline should not include the entire discussion of the issue.
second, what is the point of this issue? if the idea is to attempt to suggest that this copyright should somehow be replaced, that is a non-starter. we are not the owners of the IP, and we have not consulted with the current owners of the IP.
