### ISSUE TITLE
Clarification about UTF-8 support

### ISSUE THREAD

**Issue by cesss** [onetrueawk/awk#22]
Given that the main focus of awk is processing text, I miss some clarification in the Readme and/or in the manpage, about Unicode support. From what I have read, awk is independent from the text encoding, but I'm not really sure if that's completely true, or if some side effects or unexpected behavior could happen if awk is used in a 100% UTF-8 scenario, where everything is encoded in UTF-8, and strings with many international characters are to be expected.

Thanks a lot in advance.

**Comment by arnoldrobbins** [comment]
Some versions of awk understand multibyte encodings such as UTF-8.  Unfortunately, this version does not; each byte is treated as an individual character.  If you need Unicode support, you should probably use gawk. Hope this helps.

**Comment by cesss** [comment]
Thanks a lot, Arnold. By the way, I've found two commits adding UTF-8 support to nawk into another GitHub project: https://github.com/mturk/nawk/commits/master (unfortunately these commits not only add UTF-8 support, but also modify unrelated things, so it's not straightforward to separate the added UTF-8 support from the rest of additions/modifications --moreover, I'm not sure if this UTF-8 support is well tested -and complete- or not).

**Comment by arnoldrobbins** [comment]
I took a look at those commits. They're very Windows-specific and I have no clue what they do or how they work.

Speaking from experience, it's a fair amount of work to support multi-byte character encodings.  It could be done in nawk, but I'm not going to do it, and it involves things entirely unrelated to what was in that repo.

**Comment by onetrueawk** [comment]
It would be a major undertaking to do UTF-8 in the existing onetrueawk, unfortunately, so it's not likely to happen.

**Comment by cesss** [comment]
BTW, do you think there would be some use cases in which nawk would correctly work on UTF-8 encoded text? I’m asking this because maybe for some awk operations it doesn’t matter if the encoding of the text is UTF-8 or ASCII.

**Comment by arnoldrobbins** [comment]
`length()`, `index()` and `substr()` would generally work correctly, but they work in terms of bytes, not characters; thus `substr()` could potentially chop off a multi-byte character in the middle. Very simple regex matching would likely work but modifiers like `?`, `*`, and `+` work on the preceding byte, not the preceding character.

In short, if what's in your UTF-8 text is all ASCII, you'll be fine. Otherwise, you are likely to get bitten.  If you need to process internationalized text encoded in UTF-8, use gawk or the Open Solaris awk.

**Comment by sergeevabc** [comment]
Developers, [this][1] might interest you.

[1]: https://github.com/rmyorston/busybox-w32/issues/174#issuecomment-598390065

**Comment by arnoldrobbins** [comment]
Thanks for the pointer. It's not of much practical interest.  Unless and until someone (not me, and not BWK) volunteers to do the work, this version of awk will not support anything other than 8-bit characters.  Thanks.
