### ISSUE TITLE
a.out is what is created but where is awk?

### ISSUE THREAD

**Issue by slyfox1186** [onetrueawk/awk#220]
I ran your instruction and there was no output in the terminal window

I renamed awk: /usr/bin/awk >> /usr/bin/nawk
I ran your code in the build directory after extracting the files 'oldawk=nawk make check > check.out 2>&1'

no output was generated.

Then the directory had more files in it.

I then manually ran make

which said 'a.out' already exists.

I renamed: a.out >> awk

and you can run it like ./awk

is this what you guys had in mind?

**Comment by plan9** [comment]
the binary a.out that is generated via make is for you to install either in $HOME/bin/awk or in someplace public like /usr/local/bin/awk. that's what we had in mind. it is not intended to replace the system's own awk [may be a version of OTA, or gawk, depending on the system] in /usr/bin, but your call.

**Comment by slyfox1186** [comment]
Ok very good thank you.
