### ISSUE TITLE
Please keep tagging releases at some sort of interval

### ISSUE THREAD

**Issue by alerque** [onetrueawk/awk#222]
Revisiting #141...

We stopped getting new tags back in 2023, then the internal version date string got bumped a few more times, and now nothing.

It is an ongoing problem trying to keep this updating in downstream packaging. It's a huge waste of distro packagers time to try to hunt down if/when there is an update and whether it should actually get published. It takes a bit of research to figure out the intentions of every commit.

Please periodically at tags. They don't need to be fancy releases with changelogs or anything, just tag the repo periodically to signal the intention that "this commit is expected to work, ship this as the latest version". Ideally this would match the internal version string too so we can cross check it.

**Comment by plan9** [comment]
ok. will tag periodically.

**Comment by enh-google** [comment]
as another downstream (Android AOSP), should i only update to tagged releases, or continue to stay close to ToT?

**Comment by plan9** [comment]
latest tag is 20240311 - this is a fairly stable version.

**Comment by alerque** [comment]
Yup yup. Thanks to having a tag it turned up on my radar and I updated Arch Linux packaging yesterday.

**Comment by enh-google** [comment]
thanks! i've switched AOSP over to tags for 20240311, which means that we _won't_ take another update until there's another tag. (previously we were just taking random SHAs whenever anyone turned the crank to see if there was anything new upstream.)

**Comment by alerque** [comment]
Did you forget to tag f8be48fc79d6508189794d751e1021b91452f660 as a reelase?
