### ISSUE TITLE
mktime() support (on bsd-features branch?)

### ISSUE THREAD

**Issue by sdaoden** [onetrueawk/awk#240]
Hello!
Everybody has it but nawk (bsd-features i use):

<pre>
#?148|kent:lua.git$ busybox.static awk 'BEGIN{print mktime("2024 08 24 00 00 10")}'
1724450410
#?0|kent:lua.git$ mawk 'BEGIN{print mktime("2024 08 24 00 00 10")}'
1724450410
#?0|kent:lua.git$ gawk 'BEGIN{print mktime("2024 08 24 00 00 10")}'
1724450410
#?0|kent:lua.git$ nawk 'BEGIN{print mktime("2024 08 24 00 00 10")}'
nawk: calling undefined function mktime
 source line number 1
</pre>

The implementation of the busybox awk seems simple:

<pre>
static NOINLINE int do_mktime(const char *ds)
{
        struct tm then;
        int count;

        /*memset(&then, 0, sizeof(then)); - not needed */
        then.tm_isdst = -1; /* default is unknown */

        /* manpage of mktime says these fields are ints,
         * so we can sscanf stuff directly into them */
        count = sscanf(ds, "%u %u %u %u %u %u %d",
                &then.tm_year, &then.tm_mon, &then.tm_mday,
                &then.tm_hour, &then.tm_min, &then.tm_sec,
                &then.tm_isdst);

        if (count < 6
         || (unsigned)then.tm_mon < 1
         || (unsigned)then.tm_year < 1900
        ) {
                return -1;
        }

        then.tm_mon -= 1;
        then.tm_year -= 1900;

        return mktime(&then);
}
</pre>

**Comment by millert** [comment]
There is an implementation in OpenBSD's awk.  I could make a PR...

**Comment by sdaoden** [comment]
Thank you!  Yes, that is great, i simply copied that over and created
https://github.com/onetrueawk/awk/pull/242
which.. funnily and unplanned.. is pull request number 242.

**Comment by sdaoden** [comment]
(I close this thus.  Thanks again!)

**Comment by plan9** [comment]
> There is an implementation in OpenBSD's awk. I've cherry picked that commit as #241.

thanks todd.
