### ISSUE TITLE
Git tags not being added for releases

### ISSUE THREAD

**Issue by alerque** [onetrueawk/awk#244]
The version number in the script has been bumped at least twice since he most recently posted Git tag. This was discussed in #222 as well but it keeps happening. Can we please get tags to coincide with version bumps when you think it's appropriate for people to update? I would assume that would also coincide with the commits that bump the version string in the script.

**Comment by plan9** [comment]
hi Caleb, as I mentioned before, not every version increment is tagged. apr 22 update was tagged because of its criticality. I did not _forget_ to tag since that time, there was no overwhelming reason to. I will tag the next release because of mktime function in bsd-features. 
cheers

**Comment by plan9** [comment]
note that version 20240728 has been tagged.

**Comment by alerque** [comment]
Thanks. And Arch Linux packaging at least is updated.

Maybe don't bump the version in the script until release time? Or bump it as "YYYMMDD-dev" or something until you intend it as a release so people stop pestering us about release numbers that aren't meant actually meant to be releases...

Kolay gelsin!
