### ISSUE TITLE
Concatenating quoted and nonquoted items

### ISSUE THREAD

**Issue by nisbet-hubbard** [onetrueawk/awk#246]
The awk spec gives the following example without generalising about it:
```bash
awk '/'\''/ { print "quote:", $0 }'
```
The gawk manual puts the underlying rule thus:

> - Quoted items can be concatenated with nonquoted items as well as with other quoted items. The shell turns everything into one argument for the command.

Does this rule apply beyond programs of the form `/ regexpr / { statements }` and is expected to cover cases like `expression { statements }`, with any failure of concatenated items being parsed as one argument considered a bug?

**Comment by plan9** [comment]
the part of the gawk document you are quoting is about shell quoting issues. it has nothing to do with the awk grammar or programs of any form.
