### ISSUE TITLE
Add match groups?

### ISSUE THREAD

**Issue by vext01** [onetrueawk/awk#26]
Hi,

I was going to look at how hard it might be to add match groups to OpenBSD's awk, which turns out to be onetrueawk!

In GNU awk you can capture regex groups into an array like this:
```
match($0, pattern, ary) {print ary[1]}
```

The closest we can get in regular awk is:
```
awk 'match($0, /b[^e]*/) {print substr($0, RSTART+1, RLENGTH-1)}'
```

Which is quite cumbersome and I always have to look it up from this stackoverflow question:
https://stackoverflow.com/a/4673336/109414

Would such a feature be accepted in onetrueawk?

Thanks

**Comment by onetrueawk** [comment]
I think it would be very difficult.  The regular expression machinery in this awk is exceedingly complicated and fragile.  I think for this kind of thing, it's better to use something like Python or other language with a suitable RE library already in place.
