### ISSUE TITLE
test p.50 uses obsolete sort syntax

### ISSUE THREAD

**Issue by enh** [onetrueawk/awk#33]
specifically this line:
```
                print cc ":" pop[cc] | "sort -t: +0 -1 +2nr" }
```

fails on Android with "Unknown option 1".

i'd no idea what those options meant, but POSIX (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sort.html) says "Earlier versions of this standard also allowed the - number and + number options. These options are no longer specified by POSIX.1-2017 but may be present in some implementations."

GNU sort can actually explain what they should be translated to:
```
~$ sort --debug -t: +0 -1 +2nr
sort: using ‘en_US.UTF-8’ sorting rules
sort: obsolescent key ‘+0 -1’ used; consider ‘-k 1,1’ instead
sort: obsolescent key ‘+2’ used; consider ‘-k 3’ instead
sort: key 2 is numeric and spans multiple fields
~$ 
```

(i could send a pull request, but it seems weird and unhelpful to send a pull request that's a binary diff on a .tar file... should the .tar file actually be extracted in the git repository?)

**Comment by arnoldrobbins** [comment]
Hi. If you'll upload either a patch or a replacement version of the p.50 file, I will work to get it into the repo.

Thanks!

**Comment by mohd-akram** [comment]
Here's a patch for it:

```diff
--- testdir/p.50.orig	2018-08-22 09:50:59.000000000 +0400
+++ testdir/p.50	2019-04-07 08:20:37.157563100 +0400
@@ -1,4 +1,4 @@
 BEGIN	{ FS = "\t" }
 	{ pop[$4 ":" $1] += $3 }
 END	{ for (cc in pop)
-		print cc ":" pop[cc] | "sort -t: +0 -1 +2nr" }
+		print cc ":" pop[cc] | "sort -t: -k 1,1 -k 3nr" }
```

**Comment by arnoldrobbins** [comment]
Thanks for the patch. It's now merged in to master. Closing this issue.
