### ISSUE TITLE
Array creation

### ISSUE THREAD

**Issue by cup** [onetrueawk/awk#37]
AWK should have a variadic function for array creation. Currently if you wish to
create an array, you must use this:

~~~awk
dd[1] = "aa"
dd[2] = "bb"
dd[3] = "cc"
~~~

Or:

~~~awk
split("aa bb cc", dd)
~~~

the split syntax is problematic if your elements contain spaces. That can be
worked around by using a custom separator:

~~~awk
split("aa bb\1cc", dd, "\1")
~~~

but then it will fail again if your separator happens to be part of one of the
elements. Many other languages have syntax for array literals, for example C:

~~~c
char *dd[] = {"aa", "bb", "cc"};
~~~

Python:

~~~py
dd = ['aa', 'bb', 'cc']
~~~

JavaScript:

~~~js
var dd = ['aa', 'bb', 'cc'];
~~~

Ruby:

~~~rb
dd = ['aa', 'bb', 'cc']
~~~

Go:

~~~go
dd := []string {"aa", "bb", "cc"}
~~~

with AWK, it could look like one of these:

~~~awk
anew(dd, "aa", "bb", "cc")
dd[2] == "bb"
~~~

~~~awk
aset(dd, "aa", "bb", "cc")
dd[2] == "bb"
~~~

**Comment by onetrueawk** [comment]
This probably would have been a good idea in the early days, but after 40+ years without, it seems better to leave well enough alone.
