### ISSUE TITLE
awk doesn't accept "-v" assigns when the variable value starts with '='

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [onetrueawk/awk#38]
I have a program that passes filenames into an awk script, and recently stumbled across a problem with a filename whose first character was '='.

This caused awk to fail:
```
awk: invalid -v option argument: filename==main
```
No amount of alternate shell escaping helped, so I fixed this (and all my other awk scripts) the messy way of prefixing the variable with another, "safe", character, and then stripping it off withing the awk BEGIN section.

Looking into this, the problem is caused in lib.c, function "isclvar", where it ends as follows:
```
return *s == '=' && s > os && *(s+1) != '=';
```
Fixing this involved changing it to
```
return *s == '=' && s > os;
```
I'm unsure why the additional check for '=' is present - my only guess is that it was to stop people accidentally doing -v "varname==value"

I checked the manpages, and posix, and there's nothing mentioning this restriction, and i tested it with GNU-awk, and the problem didn't occur.

Thoughts?

 Cheers, Jamie

**Comment by arnoldrobbins** [comment]
Hi. Thanks for the note. @onetrueawk and I discussed this and it looks like you're right. I will make this fix as soon as I can. Thanks.

**Comment by arnoldrobbins** [comment]
Fixed and pushed to the repo. Thanks.

**Comment by Jamie-Landeg-Jones** [comment]
Thanks for the quick response and making the update.

Cheers, Jamie
