### ISSUE TITLE
Positional specifier causes segfault

### ISSUE THREAD

**Issue by cup** [onetrueawk/awk#4]
Gawk allows printf ordering:

~~~sh
$ awk 'BEGIN {printf "%2$s %1$s\n", "a", "b"}'
b a
~~~

and "gracefully" fails under POSIX mode:

~~~sh
$ awk --posix 'BEGIN {printf "%2$s %1$s\n", "a", "b"}'
awk: cmd. line:1: fatal: `$' is not permitted in awk formats
~~~

however BWK awk just segfaults:

~~~sh
$ awk 'BEGIN {printf "%2$s %1$s\n", "a", "b"}'
Segmentation fault (core dumped)
~~~

tested under FreeBSD

**Comment by svnpenn** [comment]
https://github.com/svnpenn/velour/issues/100

**Comment by onetrueawk** [comment]
"Fixed", by disallowing $ in format conversions, as in POSIX.   Thanks for reporting it.
