### ISSUE TITLE
Should allow unmatched parenthesis in regular expressions.

### ISSUE THREAD

**Issue by bsdimp** [onetrueawk/awk#40]
From FreeBSD bug 198552
    awk disallows the use of an unmatched right parenthesis in regular
    expressions:

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    $ awk 'BEGIN { print match("...)", ")") }'
    awk: illegal primary in regular expression ) at
     source line number 1
     context is
            BEGIN { print match("...)", >>>  ")") <<<
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    The unmatched right parenthesis should be allowed in this context, as POSIX.1-2008
    (http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_04_03)
    states the following in section 9.4.3 (ERE Special Characters):

    "The <right-parenthesis> shall be special when matched with a
    preceding <left-parenthesis>, both outside a bracket expression."

    and in section 9.5.1 (BRE/ERE Grammar Lexical Conventions)
    (http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_05_01),
    the description of the "SPEC_CHAR" token contains the following
    exception:

    "The close-parenthesis shall be considered special in this context
    only if matched with a preceding open-parenthesis."

Note: the fix in the FreeBSD bug database no longer applies, and even doing the obvious things to make it apply causes dozens of tests to fail, so obviously is a non-starter. It's also been rejected in the past by bwk.

**Comment by arnoldrobbins** [comment]
I have just pushed a fix for this issue, see commit 28dacbd66b5fb07add399e2ee9e46d85258e078d.

The fix in the FreeBSD bug database had the right idea but did it in the wrong place.  Thanks for the report. Closing the issue.
