### ISSUE TITLE
Support unary plus

### ISSUE THREAD

**Issue by cup** [onetrueawk/awk#5]
BWK awk currently does not support unary plus:

~~~sh
$ awk 'BEGIN {print +"z"}'
z
~~~

Note that Mawk and Gawk work as expected:

~~~sh
$ awk 'BEGIN {print +"z"}'
0
~~~

Further note that this is a documented violation of the POSIX standard:

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html

**Comment by onetrueawk** [comment]
Fixed.
