### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [onetrueawk/awk#56]
It is possible to migrate the personal account to organization?
- https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by arnoldrobbins** [comment]
Why are you asking? What's the point of doing so?

**Comment by Neustradamus** [comment]
https://github.com/onetrueawk is a personal account, it is better to have an organization account :)

**Comment by arnoldrobbins** [comment]
You've made an assertion but not substantiated it with facts.

What *concrete* benefits are there to @onetrueawk and myself in moving to an organization?

What *concrete* benefits are there to in moving to an organization for anyone wishes to clone the repo and/or submit pull requests?

Thanks.

**Comment by Neustradamus** [comment]
@arnoldrobbins: Easy management, ...

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t5/Support-Protips/Best-Practices-for-Organizations/ba-p/10384
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams

**Comment by arnoldrobbins** [comment]
Thanks for your interest. Neither @onetrueawk nor I see a reason to change the status quo. Thanks.

**Comment by Neustradamus** [comment]
When we see the personal account https://github.com/onetrueawk, there is not really commits.
All are done by other accounts.
Why a personal account for this project?

**Comment by arnoldrobbins** [comment]
It started out as a personal account. We see no reason to change it.

**Comment by Neustradamus** [comment]
Like several project ^^
Easy to change it.
For example: https://github.com/exiftool, ...

**Comment by arnoldrobbins** [comment]
Thanks.

**Comment by Neustradamus** [comment]
No problem, it is normal!

So you can really look for this change?

**Comment by arnoldrobbins** [comment]
No. It's not going to change. Sorry. Let's end this discussion, now, please.  Thanks.
