### ISSUE TITLE
sub with backslash in replacement string

### ISSUE THREAD

**Issue by cup** [onetrueawk/awk#6]
POSIX specifies that backslashes should undergo both lexical and runtime
processing when used as the replacement string for `sub`. Here is a correct
example using Gawk:

~~~sh
$ awk --posix 'BEGIN {$0=9; sub(9, "\\\\"); print}'
\
~~~

and incorrect example with BWK awk:

~~~sh
$ awk 'BEGIN {$0=9; sub(9, "\\\\"); print}'
\\
~~~

http://gnu.org/software/gawk/manual/html_node/Gory-Details

**Comment by arnoldrobbins** [comment]
Hi Brian.

Right now, awk is compatible with gawk's default behavior.  There's something to be said for that. On the other hand, the POSIX standard is the standard, and there's something to be said for being compatible with it.

It'd be possible to make awk pay attention to the POSIXLY_CORRECT environment variable and change behavior dynamically based on that, but I rather doubt that you want to start down that path.

If you decide that you'd prefer to be standards-compliant, let me know, and I will be happy to try to produce a pull request for you.

**Comment by cup** [comment]
@arnoldrobbins my name is not brian.

**Comment by arnoldrobbins** [comment]
Steven Penny <notifications@github.com> wrote:

> @arnoldrobbins my name is not brian.

Quite true. My comment was addressed to Brian Kernighan, whose name
is Brian, and whose repo it is.  :-)

I have been helping him out with various bug fixes to his code base.

Thanks,

Arnold Robbins
(The gawk maintainer)

**Comment by cup** [comment]
@onetrueawk why was this closed? i am not seeing recent commits
