### ISSUE TITLE
Interval expressions incorrectly handle x{0} case

### ISSUE THREAD

**Issue by arnoldrobbins** [onetrueawk/awk#60]
The One True Awk incorrectly handles interval expressions of the form `a{0}`.  For example:

```sh
$ echo abc | gawk '/ab{0}c/'
$ echo abc | nawk '/ab{0}c/'
abc
```

See the results from the new `T.int-expr` test case.

**Comment by awkfan77** [comment]
`a{0}` or `a{0,0}` seems to be equivalent to `.*`, not `a{1}`:
```sh
$ awk '/^a{0}$/'
Hello, World!
Hello, World!
$ awk '/^a{0,0}$/'
Hello, World!
Hello, World!
```

**Comment by arnoldrobbins** [comment]
I am working on a fix for this. It's all the same issue.  But this is a good test case to add to the new interval expression test script.  Thanks.

**Comment by awkfan77** [comment]
Now I think I understand what's going on, in e.g. `a{0}`, relex has already seen and returned `a` by the time it sees `{0}`, then `repeat` edits the buffer, replaces `a` with `()` and decrements `prestr` but relex sees this as 'a()', but there's also
```
if (n == 0 && m == 0) {
	return EMPTYRE;
}
```
around line 1200 in b.c that seems to remove `a` *and everything before it* (so maybe that's what's wrong), also my fix reset `prestr`.

Value of `prestr` each time `relex` scans it (with fix):
```
$ ./a.out '/a(b{0})c/'
prestr = "a(b{0})c"
prestr = "(b{0})c"
prestr = "b{0})c"
prestr = "{0})c"
repeat runs
prestr = "a(())c"
prestr = "(())c"
prestr = "())c"
prestr = "))c"
prestr = ")c"
prestr = "c"
prestr = ""
./a.out: syntax error in regular expression a(b{0})c at 
 source line number 1
 context is
	 >>> /a(b{0})c/ <<<
$ ./a.out '/^a{0}$/'
prestr = "^a{0}$"
prestr = "a{0}$"
prestr = "{0}$"
repeat runs
prestr = "^()$"
prestr = "()$"
prestr = ")$"
prestr = "$"
prestr = ""
```

Without fix:
```
$ ./a.out '/^a{0}$/'
prestr = "^a{0}$"
prestr = "a{0}$"
prestr = "{0}$"
repeat runs
prestr = "()$"
prestr = ")$"
prestr = "$"
prestr = ""
$ ./a.out '/a(b{0})c/'
prestr = "a(b{0})c"
prestr = "(b{0})c"
prestr = "b{0})c"
prestr = "{0})c"
repeat runs
prestr = "())c"
prestr = "))c"
prestr = ")c"
prestr = "c"
prestr = ""
```

**Comment by arnoldrobbins** [comment]
Pushed my fix for this.
