### ISSUE TITLE
(g)sub: backslash behaviour

### ISSUE THREAD

**Issue by McDutchie** [onetrueawk/awk#66]
```
$ gawk 'BEGIN { v="ab\\cd"; gsub(/\\/, "\\\\\\\\", v); print v; }'
ab\\cd
$ mawk 'BEGIN { v="ab\\cd"; gsub(/\\/, "\\\\\\\\", v); print v; }'
ab\\cd
$ awk 'BEGIN { v="ab\\cd"; gsub(/\\/, "\\\\\\\\", v); print v; }'
ab\\\\cd
```

The one true AWK behaves differently from both gawk and mawk when it comes to backslashes in the replacement string argument of (g)sub.

[POSIX says for gsub/sub](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html#tag_20_06_13_13): "An \<ampersand\> ( '&' ) appearing in the string *repl* shall be replaced by the string from in that matches the ERE. An \<ampersand\> preceded with a \<backslash\> shall be interpreted as the literal \<ampersand\> character. An occurrence of two consecutive \<backslash\> characters shall be interpreted as just a single literal \<backslash\> character. Any other occurrence of a \<backslash\> (for example, preceding any other character) shall be treated as a literal \<backslash\> character."

This suggests the behaviour of gawk and mawk (considering that the double quotes already remove one level of backslashes).

**Comment by McDutchie** [comment]
More info: `/usr/xpg4/bin/awk` on Solaris also acts like gawk and mawk. However, Busybox awk (at least on Busybox v1.22.1) acts like the one true AWK.

**Comment by arnoldrobbins** [comment]
Please see https://www.gnu.org/software/gawk/manual/html_node/Gory-Details.html for a detailed discussion of this issue.

It's not clear what you're requesting.  But BWK and I have discussed this before, and it's unlikely that either the one true awk nor gawk and mawk will change how they behave.

**Comment by McDutchie** [comment]
Thanks for the reference. I was unaware of the history and previous discussion.

POSIX clearly specifies one behaviour and my "request" (if my opinion matters) is that everyone should follow it, if not by default then at least in an optional standards compliance mode. Would you consider making the one true awk check for the POSIXLY_CORRECT variable and implement POSIX (g)sub behaviour if it is set?

**Comment by arnoldrobbins** [comment]
BWK and I re-discussed this. It makes sense to move to the POSIX behavior.

Please feel free to submit a PR (to the `staging` branch, please) that makes this change.  Otherwise, I will try to eventually get to it.  Thanks.

**Comment by arnoldrobbins** [comment]
OK. As of now, if POSIXLY_CORRECT exists in the environment, awk uses POSIX rules for sub and gsub.  Enjoy.

**Comment by Jamie-Landeg-Jones** [comment]
I wish POSIXLY_CORRECT was more granular!

I have that set in the environment for some other gnu programs installed, and this change bit me on a FreeBSD upgrade which contains this patch!

**Comment by McDutchie** [comment]
For a granular POSIXLY_CORRECT, you could use a dedicated directory such as `/usr/local/posix/bin` with small wrapper shell scripts such as:

```sh
export POSIXLY_CORRECT=y
exec /path/to/my/gnu/program "$@"
```

for each program you want to have that exported for. Then, instead of globally exporting POSIXLY_CORRECT, put that directory first in your `$PATH`.
