### ISSUE TITLE
syntax error with "less than"

### ISSUE THREAD

**Issue by cup** [onetrueawk/awk#7]
Example problem:

~~~
# awk 'BEGIN {print 1 < 2}'
awk: syntax error at source line 1
~~~

Workaround:

~~~
# awk 'BEGIN {print (1 < 2)}'
1
~~~

Note that Gawk and Mawk work as expected.

**Comment by onetrueawk** [comment]
This has been around since day 1, and is too deeply embedded in the grammar to be fixed by mortals.
