### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Ypnose** [onetrueawk/awk#74]
Hi there,
The last release is from 2018. Would you mind to create a new release ? It could be really useful for packagers.
Thanks

**Comment by arnoldrobbins** [comment]
We don't do releases. Anyone wanting the code should simply clone the repo and run `make`. Preferably, they should also run the tests as described in the README.md file.  Closing this issue.

Thanks.

**Comment by siraben** [comment]
Any updates on this? @arnoldrobbins @onetrueawk there are improvements such as cross-compilation fixes since the last release that would be useful to have for downstream packagers. You could also just tag the latest commit date as you did in 2018-08-27.

**Comment by siraben** [comment]
@arnoldrobbins ping
