### ISSUE TITLE
Include definition of the TF troff macro in awk.1

### ISSUE THREAD

**Issue by schragge** [onetrueawk/awk#96]
This is a cosmetic issue. The troff macro `.TF` is used in `awk.1`, but not provided by `groff`. Please consider including its definition in `awk.1` (basically taken from Plan 9 man macro package):
```
.de TF
.IP "" "\w'\fB\\$1\ \ \fP'u"
.PD 0
..
```

**Comment by arnoldrobbins** [comment]
This is done and pushed. Thanks.
